# Generated by Django 4.1.2 on 2022-12-29 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='closing_date',
            field=models.DateField(default=datetime.date(2025, 9, 24), verbose_name='closing date * '),
        ),
        migrations.AlterField(
            model_name='votingpoll',
            name='option_choice',
            field=models.BooleanField(default=True, verbose_name='A voter can leave candidates not ranked.'),
        ),
        migrations.AlterField(
            model_name='votingpoll',
            name='option_modify',
            field=models.BooleanField(default=True, verbose_name='The administrator (that is, you) can add or remove candidates whenever he / she wants.'),
        ),
        migrations.AlterField(
            model_name='votingpoll',
            name='option_shuffle',
            field=models.BooleanField(default=False, verbose_name='The winner will be chosen randomly (if there is an equality).'),
        ),
        migrations.AlterField(
            model_name='votingpoll',
            name='preference_model',
            field=models.CharField(choices=[('Approval', 'Approval Voting (Yes / No)'), ('Ranks#0', 'Simpson'), ('Ranks#2', 'Borda')], default='PositiveNegative', max_length=50, verbose_name='Preference model * '),
        ),
    ]
