# Generated by Django 4.1.2 on 2023-01-12 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='closing_date',
            field=models.DateField(default=datetime.date(2025, 10, 8), verbose_name='closing date * '),
        ),
    ]
